### ISSUE TITLE
Error when passing nothing

### ISSUE THREAD

**Issue by vjpr** [rafeca/prettyjson#44]
Should probably check that `data` is defined...

```js
console.log(prettyjson.render())
```

```
  for (var names = originalGetOPNs(object),
                   ^
TypeError: Cannot convert undefined or null to object
    at getOwnPropertyNames (<anonymous>)
    at Function.getOwnPropertyNames (/Users/Vaughan/dev-vjpr/packages/jetbrains-project/node_modules/.registry.npmjs.org/private/0.1.8/node_modules/private/private.js:72:20)
    at Object.exports.getMaxIndexLength (/Users/Vaughan/dev-vjpr/packages/jetbrains-project/node_modules/.registry.npmjs.org/prettyjson/1.2.1/node_modules/prettyjson/lib/utils.js:16:10)
    at renderToArray (/Users/Vaughan/dev-vjpr/packages/jetbrains-project/node_modules/.registry.npmjs.org/prettyjson/1.2.1/node_modules/prettyjson/lib/prettyjson.js:141:52)
    at Object.render (/Users/Vaughan/dev-vjpr/packages/jetbrains-project/node_modules/.registry.npmjs.org/prettyjson/1.2.1/node_modules/prettyjson/lib/prettyjson.js:210:10)
```

**Comment by egasimus** [comment]
This bit me. @slavaGanzin can you send a PR? @rafeca can you merge his fix?
